config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county
    # get '/state/:state_symbol/county/:std_fips_code' => 'search#county', :as => :county
    # get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    get '/my_news_item/search' => 'my_news_items#search', :as => :search_my_news_item
    post '/my_news_item/save' => 'my_news_items#save', :as => :save_my_news_item

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :representatives, only: [:show]
        resources :news_items, only: %i[index show]
        get '/representatives/my_news_item/new' => 'my_news_items#new'
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
        # get '/my_news_item/search/:representative_id/:id', to:  'my_news_items#search', :as => :search_my_news_item
        # post '/my_news_item/search/:representative_id/:id', to:  'my_news_items#save', :as => :save_my_news_item                                                   
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    # get '/my_news_item/search/:representative_id/:id', to:  'my_news_items#search', :as => :search_my_news_item
    # post '/my_news_item/search/:representative_id/:id', to:  'my_news_items#save', :as => :save_my_news_item
    
    # get '/my_news_item/search/:representative_id/:issue', to:  'my_news_items#top_5', :as => :top_5_my_news_item
    # post '/search/news_item/:id' => 'my_news_items#search', :as => :search_my_news_items
    # get '/search/(:address)' => 'representatives#search', :as => 'search_representatives'
end

app/models/representative.rb
# frozen_string_literal: true

# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all

  def self.civic_api_to_representative_params(rep_info)
    reps = []

    rep_info.officials.each_with_index do |official, index|
      ocdid_office = rep_info.offices.find { |office| office.official_indices.include?(index) }
      
      params = {
        name: official.name,
        ocdid: ocdid_office&.division_id,
        title: ocdid_office&.name,
        party: official.party,
        photo_url: official.photo_url,
        street: official.address&.first&.line1,
        city: official.address&.first&.city,
        state: official.address&.first&.state,
        zip: official.address&.first&.zip
      }

      existing_rep = Representative.find_by(name: official.name, ocdid: ocdid_office&.division_id)
      if existing_rep
        existing_rep.update(params)
        rep = existing_rep
      else
        rep = Representative.create!(params)
      end
      reps << rep
      # need to check if representative is already in database
      #unless Representative.exists?(name: official.name, ocdid: ocdid_temp,
      #    title: title_temp)
      #		rep = Representative.create!({ name: official.name, ocdid: ocdid_temp, title: title_temp })
      #		reps.push(rep)
	    # end 
    end

    reps
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def search
    address = params[:address]
    service = Google::Apis::CivicinfoV2::CivicInfoService.new
    # service.key = Rails.application.credentials.google[:GOOGLE_API_KEY]
    service.key = Rails.application.credentials.dig(Rails.env.to_sym, :GOOGLE_API_KEY)

    begin
      result = service.representative_info_by_address(address: address)
      @representatives = Representative.civic_api_to_representative_params(result)
      render 'search'
    rescue Google::Apis::Error => e
      flash[:error] = "Error searching for representatives: #{e.message}"
      redirect_to representatives_path
    end
  end

  def index
    @representatives = Representative.all
  end

  def show
    @representative = Representative.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Handle the case where the record does not exist
    redirect_to root_url, alert: 'Representative not found.'
  end

end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get, id: 'search-representatives-form' do
            .form-group.row
                .col-md-4
                    %label.col-form-label{for: 'address-field'}
                .col-md-6
                    = text_field_tag :address, nil, class: 'form-control', id: 'address-field'
            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
  .row
    .col-md-8.offset-md-2
      %h1.mt-4 Representatives for #{@address}
      
      - if @representatives.empty?
        %p.alert.alert-info No representatives found for this address.
      - else
        .table-responsive-md.pt-5
          %table.table.table-striped.table-hover#events
            %caption Table of Representatives
            %thead.thead-dark
              %tr
                %th Name
                %th Office
                %th Links
            %tbody
              - @representatives.each do |rep|
                %tr
                  %td= link_to rep.name, representative_path(rep)
                  %td= rep.title
                  %td
                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                      %i.fas.fa-newspaper
                      News Articles
      = link_to 'Back to Map', root_path, class: 'btn btn-secondary mt-3'

app/views/representatives/show.html.erb
<h1><%= @representative.name %></h1>

<div class="card">
  <div class="card-body">
    <% if @representative.photo_url.present? %>
      <%= image_tag @representative.photo_url, class: 'img-fluid mb-3', alt: @representative.name %>
    <% end %>
    <h5 class="card-title"><%= @representative.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @representative.party %></h6>
    <p class="card-text">
      <strong>OCD ID:</strong> <%= @representative.ocdid %><br>
      <strong>Address:</strong><br>
      <%= @representative.street %><br>
      <%= "#{@representative.city}, #{@representative.state} #{@representative.zip}" %>
      <%= link_to 'Back to Search', search_representatives_path, class: 'btn btn-primary mt-3' %>
    </p>
  </div>
</div>

app/views/representatives/show.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
    %h3.text-center Representative
    %h3.text-center 
    = #{@representative.name}
    %h3.text-center
    = #{@representative.ocid}
    %h3.text-center
    = #{@representative.title}

/* contact address (street, city, zip, political party, photo), political party, photo */