config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county
    # get '/state/:state_symbol/county/:std_fips_code' => 'search#county', :as => :county
    # get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    get '/my_news_item/search' => 'my_news_items#search', :as => :search_my_news_item
    post '/my_news_item/save' => 'my_news_items#save', :as => :save_my_news_item

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :representatives, only: [:show]
        resources :news_items, only: %i[index show]
        get '/representatives/my_news_item/new' => 'my_news_items#new'
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
        # get '/my_news_item/search/:representative_id/:id', to:  'my_news_items#search', :as => :search_my_news_item
        # post '/my_news_item/search/:representative_id/:id', to:  'my_news_items#save', :as => :save_my_news_item                                                   
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    # get '/my_news_item/search/:representative_id/:id', to:  'my_news_items#search', :as => :search_my_news_item
    # post '/my_news_item/search/:representative_id/:id', to:  'my_news_items#save', :as => :save_my_news_item
    
    # get '/my_news_item/search/:representative_id/:issue', to:  'my_news_items#top_5', :as => :top_5_my_news_item
    # post '/search/news_item/:id' => 'my_news_items#search', :as => :search_my_news_items
    # get '/search/(:address)' => 'representatives#search', :as => 'search_representatives'
end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

class MyNewsItemsController < SessionController
  before_action :set_representative
  before_action :set_representatives_list
  before_action :set_news_item, only: %i[edit update destroy]
  # before_action :set_issue

  # it2, pt2
  def index
    @news_items = NewsItem.all
  end

  # for it2, pt2.3
  def search
    # (:news, :title, :description, :link, :representative_id, :issue)
    # top 5 articles isn't defined in spec, so best to go by either date of creation 
    # or alphabetical order
    # begin 
    #   @issue = params[:issue]
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to representative_news_items_path(@representative), alert: 'News articles not found.'
    # end
    @issue = params[:issue]
    #TODO: query the News API and display top 5
    # News API key
    # Google::Apis::CivicinfoV2::CivicInfoService.new

    # service_key = Rails.application.credentials.dig(Rails.env.to_sym, :NEWS_API_KEY)
    service = News.new("9e9026fefdd44b9fa3552d224e2b9483")
    if service.nil?
      redirect_to representative_news_items_path(@representative), alert: 'Invalid API key.'
    end

    # @top_5_news_items = service.get_top_headlines(q: @representative.name, language: 'en', country: 'us')
    query = @representative.name + " " + @issue
    # all_articles = service.get_everything(q: query, language: 'en', country: 'us', pageSize: 5, sortBy: "popularity") 
    all_articles = service.get_everything(q: query, sortBy: "popularity") 
    arr = []
    all_articles.first(5).map do |article| 
      # arr << NewsItem.new(representative_id: @representative.ocdid, title: article.title, description: article.description, link: article.url, published_at: article.publishedAt, issue: @issue)
      arr << NewsItem.new(representative_id: @representative.ocdid, title: article.title, description: article.description, link: article.url, issue: @issue)
    end
    @top_5_news_items = arr
    # :news, :title, :description, :link, :representative_id, :issue

    # @top_5_news_items = all_articles.articles.first(5).map do |article| { title: article.title, description: article.description, link: article.url, published_at: article.publishedAt } end
    # @top_5_news_items = service
    # limit by size to 5
    # https://github.com/olegmikhnovich/News-API-ruby
    # https://newsapi.org/docs/client-libraries/ruby

    # begin
    #   result = service.representative_info_by_address(address: @address)
    #   @representatives = Representative.civic_api_to_representative_params(result)
    # rescue Google::Apis::Error => e
    #   flash[:error] = "Error searching for representatives: #{e.message}"
    #   redirect_to root_path and return
    # end


    # begin
    #   result = service.representative_info_by_address(address: address)
    #   @representatives = Representative.civic_api_to_representative_params(result)
    #   render 'search'
    # rescue Google::Apis::Error => e
    #   flash[:error] = "Error searching for representatives: #{e.message}"
    #   redirect_to representatives_path
    # end


    # @issue = params
    # begin 
    #   # top_5 = NewsItems.all.map { |r| [r.name, r.id] }
    #   @top_5_news_items = NewsItem.where(ocid: @representative.ocdid, issue: @issue).order('title desc').limit(5);
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to root_url, alert: 'News articles not found.'
    # end
  end 

  # for it2, pt2.3
  def top_5; end 

  # for it2, pt2.3
  def save
    @news_item = params
    puts params
    @news_item.save!
    redirect_to representative_news_items_path(@representative)
  end 

  # given
  def new
    @news_item = NewsItem.new
  end

  def edit; end

  def create
    @news_item = NewsItem.new(news_item_params)
    if @news_item.save
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  # def set_issue
  #   @issue = params[:issue]
  # end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :description, :link, :representative_id, :issue)
    # params.require(:news_item).permit(:news, :title, :description, :link, :representative_id)
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, @representatives_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, 'Issue', class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, ["Free Speech", "Immigration", "Terrorism", "Social Security and Medicare", "Abortion", "Student Loans", "Gun Control", "Unemployment", "Climate Change", "Homelessness", "Racism", "Tax Reform", "Net Neutrality", "Religious Freedom", "Border Security", "Minimum Wage", "Equal Pay"], { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :description, 'Description:', class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit News Item

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
        form_url: representative_new_my_news_item_path(@representative),
        form_method: :post,
        representatives_list: @representatives_list
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_items_path(@representative), class: 'btn btn-info' do
                    View news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_my_news_item_path, method: :get, id: 'search-my_news_items-form' do
            .form-group.row
                .col-sm-2
                    = label :representative_id, :representative_id, 'Representative', class: 'col-form-label', id: 'representative-field'
                .col-sm-10
                    = select_tag :representative_id, options_for_select(@representatives_list, params[:representative_id]), include_blank: true, class: 'form-control'
            .form-group.row
                .col-sm-2
                    = label :issue, 'Issue', class: 'col-form-label', id: 'issue-field'
                .col-sm-10
                    = select_tag :issue, options_for_select(["Free Speech", "Immigration", "Terrorism", "Social Security and Medicare", "Abortion", "Student Loans", "Gun Control", "Unemployment", "Climate Change", "Homelessness", "Racism", "Tax Reform", "Net Neutrality", "Religious Freedom", "Border Security", "Minimum Wage", "Equal Pay"], params[:issue]), include_blank: true, class: 'form-control'
            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/my_news_items/search.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit News Item

.col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
    = form_tag save_my_news_item_path, method: :post, id: 'select-top_5-form' do
        .form-group.row
            .col-sm-2
                = label :representative_id, :representative_id, 'Representative', class: 'col-form-label', id: 'representative-field'
            .col-sm-10
                = select_tag :representative_id, options_for_select([[@representative.name, @representative.id]]), class: 'form-control'
        .form-group.row
            .col-sm-2
                = label :issue, 'Issue', class: 'col-form-label', id: 'issue-field'
            .col-sm-10
                = select_tag :issue, options_for_select([[@issue, @issue]]), class: 'form-control'
        .form-group
            %ul
            - @top_5_news_items.each do |entry|
                %li
                    = radio_button_tag 'Article', entry.link, false, id: entry
                    = label_tag entry do
                        %span.text Title:
                        %p.text= entry.title
                        %span.text Link: 
                        %p.text= entry.link
                        %span.text Description: 
                        %p.text= entry.description
        .form-group
            = label :rating, 'Rating:'
            = select_tag :rating, options_for_select([1, 2, 3, 4, 5]), class: 'form-control'
        .actions
            = submit_tag 'Save', class: 'btn btn-primary'

    

    

        